############## PROJECT CONFIGURATION ##############

#Author: Name of the operator. Used as a prefix to avoid name collision on.
author: ""



######### EC2 Configuration #########

#Instance AWS type: Only compatible with machines that support kvm virtualization -> https://help.ubuntu.com/community/KVM/Installation.
instance_type: "c5.metal"

#AMI ID: We recommend Ubuntu "ami-035966e8adab4aaad".
ami_id: ami-035966e8adab4aaad

#EC2 Username: User name to log in to EC2 by SSH (with the previously recommended ami is "ubuntu").
ec2_username: "ubuntu"

#AWS Region.
region: "eu-west-1"

#Volume size (in GB). 10GB + 3GB * number_devices
volume_size: "20"



######### Environment Configuration #########

#Numbers of Android devices to deploy
number_devices: "2"

#Maximum CPU: maximum amount of available CPU resources each device can use 
#(We recommend a minimum of 1.5)
cpu_devices: "1.5"

#Maximum RAM:  maximum amount of memory each device can use 
#(We recommend a minimum of 3g '3GB').
ram_devices: "3g"

#Android version to use (6 to 10).
android_version: "9"

#Application Id of Android App (can find it in the 'build.graddle' file of the application).
application_id: "com.spilab.heatmapv3"

#Time to wait for the deployment of Android devices (1m '1 minute', 1h '1 hour')
#For example, for deploy 50 devices, wait 20m '20 minutes'
time_wait: "2m"

######### Logs Configuration #########

log_tags: 
  - "HeatmapLog"


######### Tests Configuration #########

## EXAMPLES
# tests:
#   - id: "test1"
#     concurrentUsers: 3
#     iterations: 5
#     delay: 500
#     url: "http://108.129.48.139/mqtt/mc/heatmaps?beginDate=2019-06-10T08:00:28Z&endDate=2019-06-10T20:56:28Z&latitude=37.378833&longitude=-5.970739&radius=600&devices=2&timeout=2500"
#   - id: "test2"
#     concurrentUsers: 3
#     iterations: 5
#     delay: 500
#     url: "http://108.129.48.139/mqtt/mc/heatmaps?beginDate=2019-06-10T08:00:28Z&endDate=2019-06-10T20:56:28Z&latitude=37.378833&longitude=-5.970739&radius=600&devices=2&timeout=2500"


#max_avg: 20000

######### Custom Tests Location #########
# custom_test: test/perses

######### Custom Tests Configuration #########
# max_avg_devices: 4000
